import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     <body className="relative min-h-screen bg-[radial-gradient(ellipse_at_top_right,#064e3b,#020617_70%)] text-white">
  <div className="absolute -z-20 inset-0 opacity-10 mix-blend-overlay pointer-events-none" />
  {children}
</body>
    </html>
  );
}
