export const storeData = {
  total: {
    revenue: 1245000,
    profit: 312000,
    customers: 8420,
    totalOrders: 11650,
    monthlySales: [
      { month: "Jan", revenue: 82000 },
      { month: "Feb", revenue: 91000 },
      { month: "Mar", revenue: 112000 },
      { month: "Apr", revenue: 95000 },
      { month: "May", revenue: 102000 },
      { month: "Jun", revenue: 108000 },
      { month: "Jul", revenue: 119000 },
      { month: "Aug", revenue: 123000 },
      { month: "Sep", revenue: 128000 },
      { month: "Oct", revenue: 135000 },
      { month: "Nov", revenue: 143000 },
      { month: "Dec", revenue: 154000 },
    ],
    topProducts: [
      { id: "p01", name: "Smartphone X12", category: "Electronics", unitsSold: 320, revenue: 128000 },
      { id: "p02", name: "Organic Apples Pack", category: "Groceries", unitsSold: 850, revenue: 10200 },
      { id: "p03", name: "Designer Handbag", category: "Fashion", unitsSold: 145, revenue: 27400 },
      { id: "p04", name: "Luxury Sofa Set", category: "Furniture", unitsSold: 35, revenue: 42000 },
      { id: "p05", name: "Face Serum", category: "Cosmetics", unitsSold: 210, revenue: 8700 },
    ],
  },

  departments: [
    {
      id: "groceries",
      name: "Groceries",
      icon: "🛒",
      color: "#00ffb0",
      revenue: 450000,
      profit: 98000,
      growth: 8,
      orders: 3250,
      avgBasket: 138,
      dailySales: [
        { day: "Mon", revenue: 15000 },
        { day: "Tue", revenue: 16500 },
        { day: "Wed", revenue: 17200 },
        { day: "Thu", revenue: 16800 },
        { day: "Fri", revenue: 19000 },
        { day: "Sat", revenue: 21000 },
        { day: "Sun", revenue: 22500 },
      ],
      categoryBreakdown: [
        { name: "Fruits & Vegetables", value: 30 },
        { name: "Dairy", value: 25 },
        { name: "Beverages", value: 20 },
        { name: "Packaged Foods", value: 15 },
        { name: "Others", value: 10 },
      ],
      insights: [
        "Peak sales between 5–7 PM.",
        "Dairy products have highest repeat purchases.",
        "Customer satisfaction rating: 4.6 / 5.",
      ],
    },
    {
      id: "electronics",
      name: "Electronics",
      icon: "💻",
      color: "#00aaff",
      revenue: 300000,
      profit: 92000,
      growth: 12,
      orders: 1840,
      avgBasket: 310,
      dailySales: [
        { day: "Mon", revenue: 11000 },
        { day: "Tue", revenue: 12000 },
        { day: "Wed", revenue: 13500 },
        { day: "Thu", revenue: 15000 },
        { day: "Fri", revenue: 17500 },
        { day: "Sat", revenue: 21000 },
        { day: "Sun", revenue: 20000 },
      ],
      categoryBreakdown: [
        { name: "Mobiles", value: 40 },
        { name: "Laptops", value: 30 },
        { name: "Accessories", value: 15 },
        { name: "Home Appliances", value: 10 },
        { name: "Others", value: 5 },
      ],
      insights: [
        "Smartphones drive 40% of total electronics revenue.",
        "Weekends see 25% higher footfall.",
        "Average customer spends $310 per order.",
      ],
    },
    {
      id: "fashion",
      name: "Fashion",
      icon: "👗",
      color: "#4ade80",
      revenue: 220000,
      profit: 47000,
      growth: 6,
      orders: 2640,
      avgBasket: 190,
      dailySales: [
        { day: "Mon", revenue: 8000 },
        { day: "Tue", revenue: 8700 },
        { day: "Wed", revenue: 9400 },
        { day: "Thu", revenue: 10000 },
        { day: "Fri", revenue: 12000 },
        { day: "Sat", revenue: 15500 },
        { day: "Sun", revenue: 14500 },
      ],
      categoryBreakdown: [
        { name: "Men", value: 35 },
        { name: "Women", value: 45 },
        { name: "Kids", value: 15 },
        { name: "Accessories", value: 5 },
      ],
      insights: [
        "Women’s fashion contributes 45% of total sales.",
        "Online orders form 60% of total revenue.",
        "Highest sales recorded on Saturdays.",
      ],
    },
    {
      id: "furniture",
      name: "Furniture",
      icon: "🪑",
      color: "#22d3ee",
      revenue: 150000,
      profit: 35000,
      growth: 9,
      orders: 960,
      avgBasket: 415,
      dailySales: [
        { day: "Mon", revenue: 5000 },
        { day: "Tue", revenue: 5300 },
        { day: "Wed", revenue: 5600 },
        { day: "Thu", revenue: 6200 },
        { day: "Fri", revenue: 6800 },
        { day: "Sat", revenue: 7700 },
        { day: "Sun", revenue: 7900 },
      ],
      categoryBreakdown: [
        { name: "Living Room", value: 35 },
        { name: "Bedroom", value: 25 },
        { name: "Office", value: 20 },
        { name: "Outdoor", value: 10 },
        { name: "Others", value: 10 },
      ],
      insights: [
        "Living room furniture sells most during festive months.",
        "High-value transactions dominate this category.",
        "Average customer purchase: $415.",
      ],
    },
    {
      id: "cosmetics",
      name: "Cosmetics",
      icon: "💄",
      color: "#60a5fa",
      revenue: 125000,
      profit: 28000,
      growth: 5,
      orders: 1750,
      avgBasket: 135,
      dailySales: [
        { day: "Mon", revenue: 4000 },
        { day: "Tue", revenue: 4200 },
        { day: "Wed", revenue: 4600 },
        { day: "Thu", revenue: 4800 },
        { day: "Fri", revenue: 5300 },
        { day: "Sat", revenue: 6000 },
        { day: "Sun", revenue: 6400 },
      ],
      categoryBreakdown: [
        { name: "Skincare", value: 40 },
        { name: "Makeup", value: 35 },
        { name: "Fragrance", value: 15 },
        { name: "Haircare", value: 10 },
      ],
      insights: [
        "Skincare is the top-selling category at 40%.",
        "High female customer retention (72%).",
        "Sales increase 20% during holiday season.",
      ],
    },
    {
      id: "home-appliances",
      name: "Home Appliances",
      icon: "🏠",
      color: "#3b82f6",
      revenue: 100000,
      profit: 24000,
      growth: 7,
      orders: 1240,
      avgBasket: 250,
      dailySales: [
        { day: "Mon", revenue: 4200 },
        { day: "Tue", revenue: 4400 },
        { day: "Wed", revenue: 4600 },
        { day: "Thu", revenue: 4900 },
        { day: "Fri", revenue: 5100 },
        { day: "Sat", revenue: 5500 },
        { day: "Sun", revenue: 5700 },
      ],
      categoryBreakdown: [
        { name: "Kitchen Appliances", value: 40 },
        { name: "Laundry", value: 25 },
        { name: "Cleaning", value: 20 },
        { name: "Other", value: 15 },
      ],
      insights: [
        "Kitchen appliances dominate with 40% of total sales.",
        "Customer satisfaction rating: 4.4 / 5.",
        "Steady growth observed across all categories.",
      ],
    },
  ],
};